#!/bin/bash

# DMENU COLORS
#
# In dwm, usually the following equivalents for dmenu coloring are:
# DMENU_FONT = dmenufont
# DMENUCOL_BG = col_gray1
# DMENUCOL_FG = col_gray3
# DMENUCOL_SELECTBG = col_gray4
# DMENUCOL_SELECTFG = col_cyan
DMENU_FONT="Microsoft Sans Serif":size=8
DMENUCOL_BG=#2A2A2A
DMENUCOL_FG=#ECECEC	
DMENUCOL_SELECTBG=#000000
DMENUCOL_SELECTFG=#70C0BA

dmenuthing() {
dmenu -i -p "$DMENU_TITLE" -fn "$DMENU_FONT" -nb "$DMENUCOL_BG" -nf "$DMENUCOL_FG" -sb "$DMENUCOL_SELECTBG" -sf "$DMENUCOL_SELECTFG"
}

function selectAction() { 
# Execute the desired action
case $1 in
    "⏻ Turn Off" | "⏻ Shutdown" | "Shutdown" | "shutdown" | "poweroff" | "Poweroff" | "Turn off" | "Turn Off" | "turn off")
	systemctl poweroff;;
" Restart" | " Reboot" | "Restart" | "restart" | "Reboot" | "reboot")
	systemctl reboot;;
"󰌆 Log Off" | "󰌆 LogOff" | "󰌆 Logoff" | "Logoff" | "logoff" | "Log Off" | "log off")
	pkill -15 dwm
	pkill -15 X;;
*) prompt=$(echo -n);;
esac
}

option=("󰌆 Log Off" "⏻ Turn Off" " Restart") 

# Show dmenu with the controls
DMENU_TITLE="Press ESC to cancel"
prompt="$(printf '%s\n' "${option[@]}" | dmenuthing)"
wait
selectAction "$prompt"
